import org.knowm.xchart.*;
import org.knowm.xchart.style.Styler;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class quickChartResult {

    final private MainFrame owner;
    private JButton backButton;
    public JPanel mainPanel;
    private JPanel chartPanel;
    private String surveyTitle = "Survey test";

    public quickChartResult(MainFrame owner) {

        super();
        this.owner = owner;
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(() -> owner.showView(new viewResultsForm(owner).mainPanel));
            }
        });
    }

    private void createUIComponents() {
        // Create Chart
        PieChart chart = new PieChartBuilder().width(0).height(0).title(surveyTitle).build();
        chartPanel = new XChartPanel<>(chart);

        Color[] sliceColors = new Color[]{
                new Color(46, 115, 69),
                new Color(46, 153, 117),
                new Color(45, 179, 179),
        }; // set colors

        chart.getStyler().setSeriesColors(sliceColors); // assign colors
        chart.getStyler().setPlotBackgroundColor(new Color(255, 255, 255, 0));
        chart.getStyler().setChartBackgroundColor(new Color(255, 255, 255, 0));

        chart.getStyler().setPlotBorderVisible(false);
        chart.getStyler().setLegendPosition(Styler.LegendPosition.InsideS);
        chart.getStyler().setChartPadding(0);
        chart.getStyler().setChartTitlePadding(0);

        chart.addSeries("Answer1", 25); // answer 1 and its size
        chart.addSeries("Answer2", 35); // answer 2 and its size
        chart.addSeries("Answer3", 40); // answer 3 and its size
        chartPanel.setMaximumSize(new Dimension(200, 200));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setAutoscrolls(false);
        mainPanel.setBackground(new Color(-7171951));
        backButton = new JButton();
        backButton.setBackground(new Color(-9343120));
        backButton.setText("Back");
        mainPanel.add(backButton, BorderLayout.SOUTH);
        chartPanel.setBackground(new Color(-7171951));
        chartPanel.setMaximumSize(new Dimension(200, 200));
        chartPanel.setVerifyInputWhenFocusTarget(false);
        mainPanel.add(chartPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
